import { Platform } from 'react-native';

export const COLORS = {
  appleBg: '#FFF8EE',
  appleSurface: '#FFFEFB',
  appleSurfaceAlt: '#F2ECFF',
  appleLine: '#E8DCCF',
  appleInk: '#2C2640',
  appleInkSoft: '#655E75',
  appleMuted: '#8B8498',
  duoGreen: '#6D4AFF',
  duoGreenDark: '#5132D5',
  duoBlue: '#32C7E5',
  duoBlueDark: '#129CB9',
  duoYellow: '#FFC94A',
  duoOrange: '#FF8A4C',
  duoRed: '#FF6666',
  duoPurple: '#9B7BFF',
  gradientApple: ['#FFFEFB', '#FFF3E4'] as const,
  gradientDuo: ['#7C5CFF', '#5937DD'] as const,
  gradientSky: ['#48D4ED', '#18A8CB'] as const,
  gradientSun: ['#FFD45B', '#FF8B48'] as const,
  gradientBerry: ['#FF7C88', '#F04E72'] as const,
  primary: '#6D4AFF',
  primaryLight: '#9B84FF',
  primaryDark: '#5132D5',
  secondary: '#FFC94A',
  secondaryLight: '#FFE18B',
  accent: '#32C7E5',
  accentLight: '#A8ECF7',
  danger: '#E84962',
  dangerLight: '#FFACB8',
  warning: '#FF8A4C',
  warningLight: '#FFD1B7',
  success: '#2DBE83',
  successLight: '#B9F1D9',
  coral: '#FF6F61',
  cream: '#FFF8EE',
  ink: '#2C2640',
  viral: '#F04E72',
  viralGlow: '#FF8CA0',
  tiktok: '#010101',
  tiktokAccent: '#69C9D0',
  bgPrimary: '#FFF8EE',
  bgSecondary: '#FFF3E4',
  bgCard: '#FFFEFB',
  bgCardLight: '#F2ECFF',
  textPrimary: '#2C2640',
  textSecondary: '#655E75',
  textMuted: '#8B8498',
  textDark: '#2C2640',
  gold: '#FFD700',
  goldDark: '#B8860B',
  silver: '#C0C0C0',
  bronze: '#CD7F32',
  gradientPurple: ['#7C5CFF', '#5937DD'] as const,
  gradientGold: ['#FFD45B', '#FF8B48'] as const,
  gradientViral: ['#FF7C88', '#F04E72'] as const,
  gradientCool: ['#48D4ED', '#18A8CB'] as const,
  gradientGreen: ['#42D69A', '#24AD76'] as const,
  gradientDark: ['#2C2640', '#1D1831'] as const,
};

export const FONTS = {
  family: {
    display: Platform.select({
      ios: 'Arial Rounded MT Bold',
      android: 'sans-serif-rounded',
      default: 'system-ui',
    }) as string,
    body: Platform.select({
      ios: 'System',
      android: 'sans-serif',
      default: 'system-ui',
    }) as string,
  },
  sizes: {
    xs: 11,
    sm: 13,
    md: 15,
    lg: 17,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    display: 42,
  },
  weights: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
    black: '900' as const,
  },
};

export const RADIUS = {
  sm: 10,
  md: 14,
  lg: 20,
  xl: 28,
  xxl: 36,
  full: 999,
};

export const SHADOWS = {
  sm: {
    shadowColor: '#4B3A73',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  md: {
    shadowColor: '#4B3A73',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 6,
  },
  lg: {
    shadowColor: '#4B3A73',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 12,
  },
  viral: {
    shadowColor: '#FF2D55',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 8,
  },
  gold: {
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
};

export const SPACING = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
};
